import { Box, Stack } from "@chakra-ui/react";
import Head from "next/head";
import React, { PropsWithChildren } from "react";
import NavBar from "./NavBar";

interface LayoutProps extends PropsWithChildren {}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box px={8}>
        <NavBar />
        <Stack align={"center"}>{children}</Stack>
      </Box>
    </>
  );
};

export default Layout;
